export const GET_PRODUCT_INFO_LOADING = 'GET_PRODUCT_INFO_LOADING'
export const GET_PRODUCT_INFO_SUCCESS = 'GET_PRODUCT_INFO_SUCCESS'
export const GET_PRODUCT_INFO_FAILURE = 'GET_PRODUCT_INFO_FAILURE'