export const GET_CHECKOUT_INFO_LOADING = 'GET_CHECKOUT_INFO_LOADING'
export const GET_CHECKOUT_INFO_SUCCESS = 'GET_CHECKOUT_INFO_SUCCESS'
export const GET_CHECKOUT_INFO_FAILURE = 'GET_CHECKOUT_INFO_FAILURE'

export const ADD_CHECKOUT_INFO_LOADING = 'ADD_CHECKOUT_INFO_LOADING'
export const ADD_CHECKOUT_INFO_SUCCESS = 'ADD_CHECKOUT_INFO_SUCCESS'
export const ADD_CHECKOUT_INFO_FAILURE = 'ADD_CHECKOUT_INFO_FAILURE'