export const GET_ORDERS_INFO_LOADING = 'GET_ORDERS_INFO_LOADING'
export const GET_ORDERS_INFO_SUCCESS = 'GET_ORDERS_INFO_SUCCESS'
export const GET_ORDERS_INFO_FAILURE = 'GET_ORDERS_INFO_FAILURE'

export const ADD_ORDER_INFO_LOADING = 'ADD_ORDER_INFO_LOADING'
export const ADD_ORDER_INFO_SUCCESS = 'ADD_ORDER_INFO_SUCCESS'
export const ADD_ORDER_INFO_FAILURE = 'ADD_ORDER_INFO_FAILURE'