export const GET_PROFILE_INFO_LOADING = 'GET_PROFILE_INFO_LOADING'
export const GET_PROFILE_INFO_SUCCESS = 'GET_PROFILE_INFO_SUCCESS'
export const GET_PROFILE_INFO_FAILURE = 'GET_PROFILE_INFO_FAILURE'

export const UPDATE_PROFILE_INFO_LOADING = 'UPDATE_PROFILE_INFO_LOADING'
export const UPDATE_PROFILE_INFO_SUCCESS = 'UPDATE_PROFILE_INFO_SUCCESS'
export const UPDATE_PROFILE_INFO_FAILURE = 'UPDATE_PROFILE_INFO_FAILURE'