export const GET_CART_INFO_LOADING = 'GET_CART_INFO_LOADING'
export const GET_CART_INFO_SUCCESS = 'GET_CART_INFO_SUCCESS'
export const GET_CART_INFO_FAILURE = 'GET_CART_INFO_FAILURE'

export const ADD_CART_INFO_LOADING = 'ADD_CART_INFO_LOADING'
export const ADD_CART_INFO_SUCCESS = 'ADD_CART_INFO_SUCCESS'
export const ADD_CART_INFO_FAILURE = 'ADD_CART_INFO_FAILURE'

export const UPDATE_CART_INFO_LOADING = 'UPDATE_CART_INFO_LOADING'
export const UPDATE_CART_INFO_SUCCESS = 'UPDATE_CART_INFO_SUCCESS'
export const UPDATE_CART_INFO_FAILURE = 'UPDATE_CART_INFO_FAILURE'

export const DELETE_CART_INFO_LOADING = 'DELETE_CART_INFO_LOADING'
export const DELETE_CART_INFO_SUCCESS = 'DELETE_CART_INFO_SUCCESS'
export const DELETE_CART_INFO_FAILURE = 'DELETE_CART_INFO_FAILURE'