export const GET_RATES_INFO_LOADING = 'GET_RATES_INFO_LOADING'
export const GET_RATES_INFO_SUCCESS = 'GET_RATES_INFO_SUCCESS'
export const GET_RATES_INFO_FAILURE = 'GET_RATES_INFO_FAILURE'

export const ADD_RATE_INFO_LOADING = 'ADD_RATE_INFO_LOADING'
export const ADD_RATE_INFO_SUCCESS = 'ADD_RATE_INFO_SUCCESS'
export const ADD_RATE_INFO_FAILURE = 'ADD_RATE_INFO_FAILURE'