export const GET_NOTIFICATIONS_INFO_LOADING = 'GET_NOTIFICATIONS_INFO_LOADING'
export const GET_NOTIFICATIONS_INFO_SUCCESS = 'GET_NOTIFICATIONS_INFO_SUCCESS'
export const GET_NOTIFICATIONS_INFO_FAILURE = 'GET_NOTIFICATIONS_INFO_FAILURE'

export const UPDATE_NOTIFICATION_INFO_LOADING = 'UPDATE_NOTIFICATION_INFO_LOADING'
export const UPDATE_NOTIFICATION_INFO_SUCCESS = 'UPDATE_NOTIFICATION_INFO_SUCCESS'
export const UPDATE_NOTIFICATION_INFO_FAILURE = 'UPDATE_NOTIFICATION_INFO_FAILURE'

// export const DELETE_BRAND_INFO_LOADING = 'DELETE_BRAND_INFO_LOADING'
// export const DELETE_BRAND_INFO_SUCCESS = 'DELETE_BRAND_INFO_SUCCESS'
// export const DELETE_BRAND_INFO_FAILURE = 'DELETE_BRAND_INFO_FAILURE'